# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps: 
- task: ServiceNow-DevOps-Agent-Artifact-Registration@1
  inputs:
    connectedServiceName: 'devops service connection'
    artifactsPayload: |
      "artifacts": [
            {
               "name": "_testdemo (1)",
               "version": "1.$(Build.BuildId)",
               "semanticVersion": "1.$(Build.BuildId).0",
               "repositoryName": "testdemo (1)"
            }
         ]
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
